basePath: /api
consumes:
- application/json
definitions:
  FileInfo:
    description: The response data of file information | 文件信息数据
    properties:
      UUID:
        description: UUID
        type: string
      createdAt:
        description: Create date | 创建日期
        format: int64
        type: integer
        x-go-name: CreatedAt
      fileType:
        description: File type | 文件类型
        type: string
        x-go-name: FileType
      id:
        description: ID
        format: int64
        type: integer
        x-go-name: ID
      name:
        description: File name | 文件名
        type: string
        x-go-name: Name
      path:
        description: File path | 文件路径
        type: string
        x-go-name: Path
      size:
        description: File size | 文件大小
        format: int64
        type: integer
        x-go-name: Size
      status:
        description: |-
          File public staus | 文件公开状态
          false private true public | false 私人, true公开
        type: boolean
        x-go-name: Status
      userUUID:
        description: User's UUID | 用户的UUID
        type: string
        x-go-name: UserUUID
    type: object
    x-go-package: github.com/suyuan32/simple-admin-file/api/internal/types
host: localhost
info:
  contact:
    email: yuansu.china.work@gmail.com
  description: This is simple admin file manager api doc
  title: Simple Admin File
  version: 0.0.1
paths:
  /core/init/database:
    get:
      description: Initialize database | 初始化数据库
      operationId: initDatabase
      responses:
        "200":
          $ref: '#/responses/SimpleMsg'
        "500":
          $ref: '#/responses/SimpleMsg'
      tags:
      - core
  /file:
    delete:
      description: Delete file information | 删除文件信息
      operationId: deleteFile
      parameters:
      - description: ID
        format: uint64
        in: query
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/SimpleMsg'
        "401":
          $ref: '#/responses/SimpleMsg'
        "500":
          $ref: '#/responses/SimpleMsg'
      tags:
      - file
  /file/download:
    get:
      description: Download file | 下载文件
      operationId: downloadFile
      parameters:
      - description: ID
        format: int64
        in: query
        name: Id
        required: true
        type: integer
      responses:
        "200":
          $ref: '#/responses/SimpleMsg'
        "401":
          $ref: '#/responses/SimpleMsg'
        "500":
          $ref: '#/responses/SimpleMsg'
      tags:
      - file
  /file/list:
    post:
      description: Update file information | 更新文件信息
      operationId: updateFile
      parameters:
      - description: ID
        format: int64
        in: query
        name: id
        required: true
        type: integer
        x-go-name: ID
      - description: File name | 文件名
        in: query
        name: name
        required: true
        type: string
        x-go-name: Name
      responses:
        "200":
          $ref: '#/responses/SimpleMsg'
        "401":
          $ref: '#/responses/SimpleMsg'
        "500":
          $ref: '#/responses/SimpleMsg'
      tags:
      - file
  /file/status:
    post:
      description: Change file public status | 改变文件公开状态
      operationId: changePublicStatus
      parameters:
      - description: ID
        format: uint64
        in: query
        name: id
        required: true
        type: integer
        x-go-name: ID
      - description: |-
          File public staus | 文件公开状态
          false private true public | false 私人, true公开
        in: query
        name: status
        required: true
        type: boolean
        x-go-name: Status
      responses:
        "200":
          $ref: '#/responses/SimpleMsg'
        "401":
          $ref: '#/responses/SimpleMsg'
        "500":
          $ref: '#/responses/SimpleMsg'
      tags:
      - file
  /upload:
    post:
      description: Upload file | 上传文件
      operationId: upload
      responses:
        "200":
          $ref: '#/responses/UploadResp'
        "401":
          $ref: '#/responses/SimpleMsg'
        "500":
          $ref: '#/responses/SimpleMsg'
      tags:
      - file
produces:
- application/json
responses:
  BaseInfo:
    description: The base response data | 基础信息
    headers:
      createdAt:
        description: Create date | 创建日期
        format: int64
        type: integer
      deletedAt:
        description: Delete date | 删除日期
        format: int64
        type: integer
      id:
        description: ID
        format: uint64
        type: integer
      updatedAt:
        description: Update date | 更新日期
        format: int64
        type: integer
  BaseMsg:
    description: The basic response without data | 基础不带数据信息
    headers:
      code:
        format: int32
        type: integer
      msg:
        type: string
  FileInfo:
    description: The response data of file information | 文件信息数据
    headers:
      UUID:
        description: UUID
        type: string
      createdAt:
        description: Create date | 创建日期
        format: int64
        type: integer
      fileType:
        description: File type | 文件类型
        type: string
      id:
        description: ID
        format: int64
        type: integer
      name:
        description: File name | 文件名
        type: string
      path:
        description: File path | 文件路径
        type: string
      size:
        description: File size | 文件大小
        format: int64
        type: integer
      status:
        description: |-
          File public staus | 文件公开状态
          false private true public | false 私人, true公开
        type: boolean
      userUUID:
        description: User's UUID | 用户的UUID
        type: string
  FileListResp:
    description: The response data of file information list | 文件信息列表数据
    headers:
      total:
        description: The total number of data | 数据总数
        format: uint64
        type: integer
    schema:
      items:
        $ref: '#/definitions/FileInfo'
      type: array
  PageList:
    description: The page response data model | 列表返回信息
    headers:
      data:
        description: Data | 数据
        items:
          type: string
        type: array
      total:
        description: Total number | 数据总数
        format: uint64
        type: integer
  SimpleMsg:
    description: The simplest message | 最简单的信息
    headers:
      msg:
        description: Message | 信息
        type: string
  UploadResp:
    description: The response data when upload finished | 上传完成返回的数据
    headers:
      msg:
        description: Message | 信息
        type: string
      name:
        description: File name | 文件名称
        type: string
      path:
        description: File path | 文件路径
        type: string
schemes:
- http
- https
swagger: "2.0"
